### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by ghost** [mubix/DeleteThatTweet#1]
After, configuring the API and consumer token key/secrets like documented, I'm getting this response with authorization:

/var/lib/gems/1.9.1/gems/twitter-5.11.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete': Twitter::Error::Unauthorized

**Comment by mubix** [comment]
Did you configure the right API keys?

**Comment by mubix** [comment]
Closing as no answer was received.
